<?php

?>

<div class="form-group">
  <label for="<?= $fieldName ?>"><?= $fieldLabel ?? $fieldName ?></label>
  <input type="<?= $fieldType ?? 'text' ?>"
         class="<?= $fieldClass ?? '' ?>"
         id="<?= $fieldName ?>"
         name="<?= $fieldName ?>"
         value="<?= $fieldValue ?? '' ?>"
    <?php
    if (isset($fieldSize)) {
      foreach (["min", "max", "minlength", "maxlength"] as $prop) {
        if (array_key_exists($prop, $fieldSize)) {
          echo $prop . "=" . "\"" . $fieldSize[$prop] . "\"";
        }
      }
    }
    echo implode(" ", [ ($fieldRequired ?? ""), ($fieldReadonly ?? "") ])
    ?>>
</div>
