<?php

use framework\Router;
use framework\Tools;

?>
<!doctype html>
<html lang="fr">
<head>
  <meta charset="UTF-8">
  <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title><?= APP_NAME ?></title>
  <link rel="stylesheet" href="/assets/bootstrap/dist/css/bootstrap.css">
  <link rel="stylesheet" href="/assets/select2/dist/css/select2.min.css">
  <link rel="stylesheet" href="/assets/jquery-confirm/dist/jquery-confirm.min.css">
</head>
<body class="container-fluid">
<header class="card-header row">
  <div class="col-4">
    <h3 title="<?= DSN ?>"><?= APP_NAME ?></h3>
  </div>
  <div class="col-4 text-center">
    <?php if (isset($fm)) : ?>
      <h3><?= $fm->getTitle() ?></h3>
    <?php else : ?>
      <h3><?= $title ?? "" ?></h3>
    <?php endif; ?>
  </div>
  <div class="col-4 text-right">
    <ul class="nav nav-pills">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown">
          Menu 1
        </a>
        <div class="dropdown-menu">
          <a class="dropdown-item" href="<?= Router::route(['route.1.1']) ?>">SubMenu 1.1</a>
          <a class="dropdown-item" href="<?= Router::route(['route.1.2']) ?>">SubMenu 1.2</a>
          <a class="dropdown-item" href="<?= Router::route(['route.1.3']) ?>">SubMenu 1.3</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown">
          Menu 2
        </a>
        <div class="dropdown-menu">
          <a class="dropdown-item" href="<?= Router::route(['route.2.1']) ?>">SubMenu 2.1</a>
          <a class="dropdown-item" href="<?= Router::route(['route.2.2']) ?>">SubMenu 2.2</a>
          <a class="dropdown-item" href="<?= Router::route(['route.2.3']) ?>">SubMenu 2.3</a>
        </div>
      </li>
    </ul>
  </div>
</header>

<div class="row justify-content-center">

  <?php
  $messages = Tools::getFlash();
  if (is_array($messages) && count($messages) > 0) : ?>
    <div class="alert alert-success alert-dismissible fade show col-md-6 mt-2" role="alert">
      <button type="button" class="close" data-dismiss="alert">
        <span>&times;</span>
      </button>
      <ul>
        <?php foreach ($messages as $message) : ?>
          <li><?= $message ?></li>
        <?php endforeach; ?>
      </ul>
    </div>
  <?php endif ?>

  <?php
  $messages = Tools::getFlash("warning");
  if (is_array($messages) && count($messages) > 0) : ?>
    <div class="alert alert-warning alert-dismissible fade show col-md-6 mt-2" role="alert">
      <button type="button" class="close" data-dismiss="alert">
        <span>&times;</span>
      </button>
      <ul>
        <?php foreach ($messages as $message) : ?>
          <li><?= $message ?></li>
        <?php endforeach; ?>
      </ul>
    </div>
  <?php endif ?>

  <?php
  $messages = Tools::getFlash("error");
  if (is_array($messages) && count($messages) > 0) : ?>
    <div class="alert alert-danger alert-dismissible fade show col-md-6 mt-2" role="alert">
      <button type="button" class="close" data-dismiss="alert">
        <span>&times;</span>
      </button>
      <ul>
        <?php foreach ($messages as $message) : ?>
          <li><?= $message ?></li>
        <?php endforeach; ?>
      </ul>
      <button type="button" class="close"></button>
    </div>
  <?php endif ?>
</div>

<div class="row justify-content-center">
  <?= $content ?>
</div>

<script src="/assets/jquery/dist/jquery.slim.js"></script>
<script src="/assets/popper.js/dist/umd/popper.js"></script>
<script src="/assets/bootstrap/dist/js/bootstrap.js"></script>
<script src="/assets/select2/dist/js/select2.min.js"></script>
<script src="/assets/jquery-confirm/dist/jquery-confirm.min.js"></script>
<script src="https://kit.fontawesome.com/fff1f19af2.js"></script>

<script src="/js/utils.js"></script>

<script>
  <?php if ($script) : ?>
  <?php include $script ?>
  <?php endif; ?>
</script>

</body>
</html>